### ISSUE TITLE
whedon can't compile "buried" paper

### ISSUE THREAD

**Issue by WilkAndy** [openjournals/whedon#63] opened 2020-02-26 02:23 UTC
I submitted an article to JOSS.   The repo I provided is

 https://github.com/idaholab/moose/tree/master/modules/porous_flow

and paper.md is sitting there:

 https://github.com/idaholab/moose/tree/master/modules/porous_flow/paper.md

However, the command `@whedon generate pdf` returns

```
sh: 1: cd: can't cd to tmp/2118
/app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in block in find': No such file or directory - tmp/2118 (Errno::ENOENT) from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in collect!'
from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in find' from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/lib/whedon/processor.rb:61:in find_paper_paths'
from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/bin/whedon:50:in prepare' from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in run'
from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in invoke_command' from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in dispatch'
from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in start' from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-29ce1a232aa1/bin/whedon:116:in <top (required)>'
from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in load' from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in 
```

The same paper, sitting in repo

https://github.com/WilkAndy/PorousFlowDescription

compiles fine.

**Comment by arfon** [comment] 2020-03-21 01:01
Closing as a dupe of #60

**Closed** 2020-03-21 01:01 UTC
