### ISSUE TITLE
Submission and Acceptance dates

### ISSUE THREAD

**Issue by rgieseke** [openjournals/whedon#15] opened 2017-11-30 17:17 UTC
Would it be possible to add submission and acceptance dates to the output?

There are recoverable from the GitHub issue but would be nice to have them in the PDF and webpage. (And also probably interesting for analysis.)

**Comment by arfon** [comment] 2017-12-01 13:58
@rgieseke - yes I'd like to get these added. I *think* this issue is a duplicate of another but I've added it to the backlog nonetheless.

**Comment by rgieseke** [comment] 2017-12-01 14:02
Found it, in the JOSS repo: https://github.com/openjournals/joss/issues/342

Would be really nice to have!

**Comment by arfon** [comment] 2017-12-01 14:06
Ah yes. Nice work. I'm going to close this as a dup of https://github.com/openjournals/joss/issues/342 then.

**Closed by arfon** 2017-12-01 14:06 UTC
Labels: enhancement
